lcm_monitoring.settings:
  type: config_object
  label: "LCM monitoring settings"
  mapping:
    projectid:
      type: string
      label: "Project ID"
    accesskey:
      type: string
      label: "Access key"
    logger:
      type: mapping
      mapping:
        enabled:
          type: boolean
          label: "Activate Logger"
        host:
          type: string
          label: "Logger host"
        port:
          type: integer
          label: "Logger port"
